// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Article: typeof import('./ui/components/Article.vue')['default']
    AuthSignInForm: typeof import('./ui/components/forms/AuthSignInForm.vue')['default']
    AuthSignUpForm: typeof import('./ui/components/forms/AuthSignUpForm.vue')['default']
    Buttons: typeof import('./ui/components/Buttons.vue')['default']
    DescriptionCard: typeof import('./ui/components/DescriptionCard.vue')['default']
    DocInfo: typeof import('./ui/components/DocInfo.vue')['default']
    FeatureSection: typeof import('./ui/components/FeatureSection.vue')['default']
    FeatureSectionAlt: typeof import('./ui/components/FeatureSectionAlt.vue')['default']
    Footer: typeof import('./ui/components/nav/Footer.vue')['default']
    Header: typeof import('./ui/components/nav/Header.vue')['default']
    HeaderAlt: typeof import('./ui/components/nav/HeaderAlt.vue')['default']
    HelloWorld: typeof import('./ui/components/HelloWorld.vue')['default']
    HelpCard: typeof import('./ui/components/card/HelpCard.vue')['default']
    HeroSection: typeof import('./ui/components/nav/HeroSection.vue')['default']
    IHeroiconsOutlineChevronDown: typeof import('~icons/heroicons-outline/chevron-down')['default']
    IHeroiconsOutlineMenu: typeof import('~icons/heroicons-outline/menu')['default']
    IHeroiconsOutlineX: typeof import('~icons/heroicons-outline/x')['default']
    ImageCard: typeof import('./ui/components/card/ImageCard.vue')['default']
    ImageCardAlt: typeof import('./ui/components/card/ImageCardAlt.vue')['default']
    ImageOverlayCard: typeof import('./ui/components/card/ImageOverlayCard.vue')['default']
    InfoCard: typeof import('./ui/components/InfoCard.vue')['default']
    InfoCardAlt: typeof import('./ui/components/InfoCardAlt.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverGroup: typeof import('@headlessui/vue')['PopoverGroup']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    ProfileCard: typeof import('./ui/components/card/ProfileCard.vue')['default']
    ProfileCardSimple: typeof import('./ui/components/card/ProfileCardSimple.vue')['default']
    QuoteBox: typeof import('./ui/components/QuoteBox.vue')['default']
    StripeCarousel: typeof import('./ui/components/carousel/StripeCarousel.vue')['default']
    TestimonialCard: typeof import('./ui/components/card/TestimonialCard.vue')['default']
  }
}

export { }
